# Generated by Django 3.0.3 on 2020-05-14 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafty_devil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 12, 42, 14, 835419)),
        ),
    ]
