# Generated by Django 3.0.3 on 2020-05-15 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafty_devil', '0002_auto_20200514_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 19, 26, 10, 605445)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='security_number',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
