# Generated by Django 3.0.3 on 2020-05-15 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafty_devil', '0003_auto_20200515_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 23, 8, 7, 970120)),
        ),
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
